"use client";

import React from "react";
import { useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import { Id } from "@/convex/_generated/dataModel";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  ArrowLeft,
  Calendar,
  Sun,
  Moon,
  Eye,
  Download,
  FileText
} from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger
} from "@/components/ui/dialog";
import { useRouter } from "next/navigation";
import { toast } from "sonner";

type DocumentsPageProps = {
  params: Promise<{ id: string }>;
};

export default function DocumentsPage({ params }: DocumentsPageProps) {
  const { id } = React.use(params);
  const router = useRouter();
  const [selectedReport, setSelectedReport] = React.useState<{
    type: 'day' | 'night';
    date: string;
    activities: any[];
  } | null>(null);

  const resident = useQuery(api.residents.getById, {
    residentId: id as Id<"residents">
  });

  // Get today's date for current reports
  const today = new Date().toISOString().split('T')[0];
  const currentHour = new Date().getHours();

  // Get day report (8 AM - 8 PM logs)
  const dayReport = useQuery(api.personalCare.getDayNightReport, {
    residentId: id as Id<"residents">,
    date: today,
    reportType: "day"
  });

  // Get night report (8 PM - 8 AM logs)  
  const nightReport = useQuery(api.personalCare.getDayNightReport, {
    residentId: id as Id<"residents">,
    date: today,
    reportType: "night"
  });

  const handleViewReport = (type: 'day' | 'night') => {
    const report = type === 'day' ? dayReport : nightReport;
    if (report) {
      setSelectedReport({
        type,
        date: today,
        activities: report.activities || []
      });
    }
  };

  const handleDownloadReport = async (type: 'day' | 'night') => {
    try {
      const report = type === 'day' ? dayReport : nightReport;
      if (!report || !resident) {
        toast.error('No report data available');
        return;
      }

      // Generate PDF content
      const pdfContent = generatePDFContent({
        resident,
        report,
        type,
        date: today
      });

      // Create and download PDF
      downloadTextAsPDF(
        pdfContent,
        `${resident.firstName}_${resident.lastName}_${type}_report_${today}.pdf`
      );

      toast.success(`${type === 'day' ? 'Day' : 'Night'} report downloaded successfully`);
    } catch {
      toast.error('Failed to download report');
    }
  };

  const generatePDFContent = ({
    resident,
    report,
    type,
    date
  }: {
    resident: any;
    report: any;
    type: 'day' | 'night';
    date: string;
  }) => {
    const timeRange = type === 'day' ? '8:00 AM - 8:00 PM' : '8:00 PM - 8:00 AM';
    const shiftName = type === 'day' ? 'Day' : 'Night';
    
    let content = `DAILY CARE REPORT - ${shiftName.toUpperCase()} SHIFT\n\n`;
    content += `Resident: ${resident.firstName} ${resident.lastName}\n`;
    content += `Date: ${new Date(date).toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })}\n`;
    content += `Shift Period: ${timeRange}\n`;
    content += `Generated: ${new Date().toLocaleString()}\n\n`;
    
    content += `SUMMARY\n`;
    content += `Total Activities: ${report.activities?.length || 0}\n`;
    const completedCount = report.activities?.filter((a: any) => a.status === 'completed').length || 0;
    content += `Completed Activities: ${completedCount}\n`;
    if (report.activities?.length > 0) {
      content += `Completion Rate: ${Math.round((completedCount / report.activities.length) * 100)}%\n`;
    }
    content += `\n`;

    if (report.activities && report.activities.length > 0) {
      content += `ACTIVITIES LOG\n\n`;
      
      report.activities.forEach((activity: any, index: number) => {
        content += `${index + 1}. ${activity.taskType}\n`;
        content += `   Status: ${activity.status}\n`;
        if (activity.completedAt) {
          content += `   Time: ${new Date(activity.completedAt).toLocaleTimeString()}\n`;
        }
        if (activity.notes) {
          content += `   Notes: ${activity.notes}\n`;
        }
        content += `\n`;
      });
    } else {
      content += `No activities logged for this ${type} shift.\n\n`;
    }

    content += `\nThis report was automatically generated by the Care Management System.`;
    
    return content;
  };

  const downloadTextAsPDF = (content: string, filename: string) => {
    // Simple text-based PDF alternative - create a downloadable text file
    // In a real implementation, you'd use a library like jsPDF
    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename.replace('.pdf', '.txt');
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  if (resident === undefined) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto"></div>
          <p className="mt-2 text-muted-foreground">Loading resident...</p>
        </div>
      </div>
    );
  }

  if (resident === null) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-center">
          <p className="text-lg font-semibold">Resident not found</p>
          <p className="text-muted-foreground">
            The resident you&apos;re looking for doesn&apos;t exist.
          </p>
          <Button
            variant="outline"
            className="mt-4"
            onClick={() => router.back()}
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Go Back
          </Button>
        </div>
      </div>
    );
  }

  const fullName = `${resident.firstName} ${resident.lastName}`;

  return (
    <div className="container mx-auto p-6 space-y-6 max-w-4xl">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-4">
          <Button variant="outline" size="icon" onClick={() => router.back()}>
            <ArrowLeft className="w-4 h-4" />
          </Button>
          <div className="flex items-center space-x-4">
            <div className="p-2 bg-blue-100 rounded-lg">
              <FileText className="w-6 h-6 text-blue-600" />
            </div>
            <div>
              <h1 className="text-2xl font-bold">Daily Care Documents</h1>
              <p className="text-muted-foreground">
                Day and Night shift reports for {fullName}
              </p>
            </div>
          </div>
        </div>
        <Button
          variant="outline"
          onClick={() => router.push(`/dashboard/residents/${id}/daily-care`)}
          className="flex items-center space-x-2"
        >
          <Calendar className="w-4 h-4" />
          <span>Back to Daily Care</span>
        </Button>
      </div>

      {/* Current Date */}
      <Card>
        <CardHeader className="pb-4">
          <CardTitle className="flex items-center space-x-2">
            <Calendar className="w-5 h-5" />
            <span>Today&apos;s Reports - {new Date(today).toLocaleDateString("en-US", {
              weekday: "long",
              year: "numeric", 
              month: "long",
              day: "numeric"
            })}</span>
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Day Report */}
            <Card className="border-2">
              <CardHeader className="pb-4">
                <CardTitle className="flex items-center space-x-2 text-lg">
                  <Sun className="w-5 h-5 text-amber-600" />
                  <span>Day Report</span>
                </CardTitle>
                <p className="text-sm text-muted-foreground">
                  8:00 AM - 8:00 PM
                </p>
              
              </CardHeader>
              <CardContent className="space-y-3">
                {currentHour >= 20 ? (
                  <p className="text-sm text-green-600 font-medium">
                    ✓ Report automatically generated at 8:00 PM
                  </p>
                ) : (
                  <p className="text-sm text-blue-600">
                    Report will be generated at 8:00 PM
                  </p>
                )}
                
                <div className="flex space-x-2">
                  <Dialog>
                    <DialogTrigger asChild>
                      <Button 
                        variant="outline" 
                        className="flex-1"
                        onClick={() => handleViewReport('day')}
                        disabled={!dayReport}
                      >
                        <Eye className="w-4 h-4 mr-2" />
                        View
                      </Button>
                    </DialogTrigger>
                    <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
                      <DialogHeader>
                        <DialogTitle className="flex items-center space-x-2">
                          <Sun className="w-5 h-5 text-amber-600" />
                          <span>Day Report - {new Date(today).toLocaleDateString()}</span>
                        </DialogTitle>
                        <DialogDescription>
                          All activities logged from 8:00 AM to 8:00 PM
                        </DialogDescription>
                      </DialogHeader>
                      
                      <div className="space-y-4">
                        {selectedReport?.type === 'day' && (
                          <div className="space-y-3">
                            <div className="grid grid-cols-3 gap-4 p-4 bg-amber-50 border border-amber-200 rounded-lg">
                              <div>
                                <h4 className="font-medium text-amber-800">Shift Period</h4>
                                <p className="text-sm text-amber-700">8:00 AM - 8:00 PM</p>
                              </div>
                              <div>
                                <h4 className="font-medium text-amber-800">Total Activities</h4>
                                <p className="text-sm text-amber-700">{selectedReport.activities.length}</p>
                              </div>
                              <div>
                                <h4 className="font-medium text-amber-800">Completion Rate</h4>
                                <p className="text-sm text-amber-700">
                                  {selectedReport.activities.length > 0 
                                    ? Math.round((selectedReport.activities.filter(a => a.status === 'completed').length / selectedReport.activities.length) * 100)
                                    : 0}%
                                </p>
                              </div>
                            </div>

                            <div className="space-y-2">
                              <h4 className="font-medium">Activities Log</h4>
                              {selectedReport.activities.length > 0 ? (
                                <div className="space-y-2 max-h-60 overflow-y-auto">
                                  {selectedReport.activities.map((activity, index) => (
                                    <div key={index} className="p-3 border border-gray-200 rounded-lg">
                                      <div className="flex justify-between items-start">
                                        <div>
                                          <p className="font-medium">{activity.taskType}</p>
                                          <p className="text-sm text-muted-foreground">
                                            {activity.completedAt ? new Date(activity.completedAt).toLocaleTimeString() : 'Pending'}
                                          </p>
                                          {activity.notes && (
                                            <p className="text-sm text-gray-600 mt-1">{activity.notes}</p>
                                          )}
                                        </div>
                                        <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                                          activity.status === 'completed' 
                                            ? 'bg-green-100 text-green-800'
                                            : 'bg-yellow-100 text-yellow-800'
                                        }`}>
                                          {activity.status}
                                        </span>
                                      </div>
                                    </div>
                                  ))}
                                </div>
                              ) : (
                                <p className="text-muted-foreground py-8 text-center">No activities logged for day shift</p>
                              )}
                            </div>
                          </div>
                        )}
                      </div>
                    </DialogContent>
                  </Dialog>
                  
                  <Button 
                    variant="default"
                    className="flex-1"
                    onClick={() => handleDownloadReport('day')}
                    disabled={!dayReport}
                  >
                    <Download className="w-4 h-4 mr-2" />
                    Download PDF
                  </Button>
                </div>
              </CardContent>
            </Card>

            {/* Night Report */}
            <Card className="border-2">
              <CardHeader className="pb-4">
                <CardTitle className="flex items-center space-x-2 text-lg">
                  <Moon className="w-5 h-5 text-indigo-600" />
                  <span>Night Report</span>
                </CardTitle>
                <p className="text-sm text-muted-foreground">
                  8:00 PM - 8:00 AM
                </p>
              
              </CardHeader>
              <CardContent className="space-y-3">
                {currentHour >= 8 && currentHour < 20 ? (
                  <p className="text-sm text-green-600 font-medium">
                    ✓ Report automatically generated at 8:00 AM
                  </p>
                ) : (
                  <p className="text-sm text-indigo-600">
                    Report will be generated at 8:00 AM
                  </p>
                )}
                
                <div className="flex space-x-2">
                  <Dialog>
                    <DialogTrigger asChild>
                      <Button 
                        variant="outline" 
                        className="flex-1"
                        onClick={() => handleViewReport('night')}
                        disabled={!nightReport}
                      >
                        <Eye className="w-4 h-4 mr-2" />
                        View
                      </Button>
                    </DialogTrigger>
                    <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
                      <DialogHeader>
                        <DialogTitle className="flex items-center space-x-2">
                          <Moon className="w-5 h-5 text-indigo-600" />
                          <span>Night Report - {new Date(today).toLocaleDateString()}</span>
                        </DialogTitle>
                        <DialogDescription>
                          All activities logged from 8:00 PM to 8:00 AM
                        </DialogDescription>
                      </DialogHeader>
                      
                      <div className="space-y-4">
                        {selectedReport?.type === 'night' && (
                          <div className="space-y-3">
                            <div className="grid grid-cols-3 gap-4 p-4 bg-indigo-50 border border-indigo-200 rounded-lg">
                              <div>
                                <h4 className="font-medium text-indigo-800">Shift Period</h4>
                                <p className="text-sm text-indigo-700">8:00 PM - 8:00 AM</p>
                              </div>
                              <div>
                                <h4 className="font-medium text-indigo-800">Total Activities</h4>
                                <p className="text-sm text-indigo-700">{selectedReport.activities.length}</p>
                              </div>
                              <div>
                                <h4 className="font-medium text-indigo-800">Completion Rate</h4>
                                <p className="text-sm text-indigo-700">
                                  {selectedReport.activities.length > 0 
                                    ? Math.round((selectedReport.activities.filter(a => a.status === 'completed').length / selectedReport.activities.length) * 100)
                                    : 0}%
                                </p>
                              </div>
                            </div>

                            <div className="space-y-2">
                              <h4 className="font-medium">Activities Log</h4>
                              {selectedReport.activities.length > 0 ? (
                                <div className="space-y-2 max-h-60 overflow-y-auto">
                                  {selectedReport.activities.map((activity, index) => (
                                    <div key={index} className="p-3 border border-gray-200 rounded-lg">
                                      <div className="flex justify-between items-start">
                                        <div>
                                          <p className="font-medium">{activity.taskType}</p>
                                          <p className="text-sm text-muted-foreground">
                                            {activity.completedAt ? new Date(activity.completedAt).toLocaleTimeString() : 'Pending'}
                                          </p>
                                          {activity.notes && (
                                            <p className="text-sm text-gray-600 mt-1">{activity.notes}</p>
                                          )}
                                        </div>
                                        <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                                          activity.status === 'completed' 
                                            ? 'bg-green-100 text-green-800'
                                            : 'bg-yellow-100 text-yellow-800'
                                        }`}>
                                          {activity.status}
                                        </span>
                                      </div>
                                    </div>
                                  ))}
                                </div>
                              ) : (
                                <p className="text-muted-foreground py-8 text-center">No activities logged for night shift</p>
                              )}
                            </div>
                          </div>
                        )}
                      </div>
                    </DialogContent>
                  </Dialog>
                  
                  <Button 
                    variant="default"
                    className="flex-1"
                    onClick={() => handleDownloadReport('night')}
                    disabled={!nightReport}
                  >
                    <Download className="w-4 h-4 mr-2" />
                    Download PDF
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>
        </CardContent>
      </Card>

      {/* Information Card */}
      <Card className="border-blue-200 bg-blue-50">
        <CardContent className="p-4">
          <h3 className="font-medium text-blue-900 mb-2">How Reports Work</h3>
          <div className="space-y-1 text-sm text-blue-800">
            <p>• <strong>Day Report:</strong> Automatically generated at 8:00 PM with all activities from 8:00 AM - 8:00 PM</p>
            <p>• <strong>Night Report:</strong> Automatically generated at 8:00 AM with all activities from 8:00 PM - 8:00 AM</p>
            <p>• Reports include all logged care activities, completion status, and staff notes</p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}