"use client";

import React from "react";
import { useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import { Id } from "@/convex/_generated/dataModel";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  ArrowLeft,
  Sun,
  Moon,
  Eye,
  Download,
  Calendar,
  Search
} from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger
} from "@/components/ui/dialog";
import { useRouter } from "next/navigation";
import { toast } from "sonner";

type DocumentsPageProps = {
  params: Promise<{ id: string }>;
};

export default function DocumentsPage({ params }: DocumentsPageProps) {
  const { id } = React.use(params);
  const router = useRouter();
  const [selectedReport, setSelectedReport] = React.useState<{
    type: 'day' | 'night';
    date: string;
    activities: any[];
  } | null>(null);
  const [dateFilter, setDateFilter] = React.useState<string>("");

  const resident = useQuery(api.residents.getById, {
    residentId: id as Id<"residents">
  });

  // Get all available report dates for this resident
  const availableDates = useQuery(api.personalCare.getAvailableReportDates, {
    residentId: id as Id<"residents">
  });

  // Get the selected report data when viewing
  const selectedReportData = useQuery(
    api.personalCare.getDayNightReport,
    selectedReport ? {
      residentId: id as Id<"residents">,
      date: selectedReport.date,
      reportType: selectedReport.type
    } : "skip"
  );

  // Filter dates based on search
  const filteredDates = React.useMemo(() => {
    if (!availableDates) return [];
    if (!dateFilter) return availableDates;
    
    return availableDates.filter(date => 
      date.includes(dateFilter) || 
      new Date(date).toLocaleDateString().includes(dateFilter)
    );
  }, [availableDates, dateFilter]);

  const handleViewReport = (date: string, type: 'day' | 'night') => {
    // Set the selected report state - the dialog will handle loading the data
    setSelectedReport({
      type,
      date,
      activities: [] // Will be loaded by the useQuery hook
    });
  };

  const handleDownloadReport = (date: string, type: 'day' | 'night') => {
    if (!resident) {
      toast.error('Resident data not available');
      return;
    }

    // Use the currently loaded report data if available, otherwise create a mock
    const reportToDownload = selectedReportData && selectedReport?.date === date && selectedReport?.type === type 
      ? selectedReportData 
      : { activities: [], reportGenerated: false };

    const pdfContent = generatePDFContent({
      resident,
      report: reportToDownload,
      type,
      date
    });

    downloadTextAsPDF(
      pdfContent,
      `${resident.firstName}_${resident.lastName}_${type}_report_${date}.pdf`
    );

    toast.success(`${type === 'day' ? 'Day' : 'Night'} report downloaded successfully`);
  };

  const generatePDFContent = ({
    resident,
    report,
    type,
    date
  }: {
    resident: any;
    report: any;
    type: 'day' | 'night';
    date: string;
  }) => {
    const timeRange = type === 'day' ? '8:00 AM - 8:00 PM' : '8:00 PM - 8:00 AM';
    const shiftName = type === 'day' ? 'Day' : 'Night';
    
    let content = `DAILY CARE REPORT - ${shiftName.toUpperCase()} SHIFT\n\n`;
    content += `Resident: ${resident.firstName} ${resident.lastName}\n`;
    content += `Date: ${new Date(date).toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })}\n`;
    content += `Shift Period: ${timeRange}\n`;
    content += `Generated: ${new Date().toLocaleString()}\n\n`;
    
    content += `SUMMARY\n`;
    content += `Total Activities: ${report.activities?.length || 0}\n`;
    const completedCount = report.activities?.filter((a: any) => a.status === 'completed').length || 0;
    content += `Completed Activities: ${completedCount}\n`;
    if (report.activities?.length > 0) {
      content += `Completion Rate: ${Math.round((completedCount / report.activities.length) * 100)}%\n`;
    }
    content += `\n`;

    if (report.activities && report.activities.length > 0) {
      content += `ACTIVITIES LOG\n\n`;
      
      report.activities.forEach((activity: any, index: number) => {
        content += `${index + 1}. ${activity.taskType}\n`;
        content += `   Status: ${activity.status}\n`;
        if (activity.completedAt) {
          content += `   Time: ${new Date(activity.completedAt).toLocaleTimeString()}\n`;
        }
        if (activity.notes) {
          content += `   Notes: ${activity.notes}\n`;
        }
        content += `\n`;
      });
    } else {
      content += `No activities logged for this ${type} shift.\n\n`;
    }

    content += `\nThis report was automatically generated by the Care Management System.`;
    
    return content;
  };

  const downloadTextAsPDF = (content: string, filename: string) => {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename.replace('.pdf', '.txt');
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  if (resident === undefined) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto"></div>
          <p className="mt-2 text-muted-foreground">Loading resident...</p>
        </div>
      </div>
    );
  }

  if (resident === null) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-center">
          <p className="text-lg font-semibold">Resident not found</p>
          <p className="text-muted-foreground">
            The resident you&apos;re looking for doesn&apos;t exist.
          </p>
          <Button
            variant="outline"
            className="mt-4"
            onClick={() => router.back()}
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Go Back
          </Button>
        </div>
      </div>
    );
  }

  const fullName = `${resident.firstName} ${resident.lastName}`;

  return (
    <div className="container mx-auto p-6 space-y-6 max-w-6xl">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-4">
          <Button variant="outline" size="icon" onClick={() => router.back()}>
            <ArrowLeft className="w-4 h-4" />
          </Button>
          <div>
            <h1 className="text-2xl font-bold">Daily Care Documents</h1>
            <p className="text-muted-foreground">
              All archived reports for {fullName}
            </p>
          </div>
        </div>
      </div>

      {/* Date Filter */}
      <div className="flex items-center space-x-4 mb-6">
        <div className="relative flex-1 max-w-sm">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground w-4 h-4" />
          <Input
            placeholder="Search by date (e.g., 2024-01-15 or Jan 15)"
            value={dateFilter}
            onChange={(e) => setDateFilter(e.target.value)}
            className="pl-10"
          />
        </div>
        <p className="text-sm text-muted-foreground">
          {filteredDates?.length || 0} report dates found
        </p>
      </div>

      {/* Reports List */}
      {availableDates === undefined ? (
        <div className="flex items-center justify-center py-12">
          <div className="text-center">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto"></div>
            <p className="mt-2 text-muted-foreground">Loading reports...</p>
          </div>
        </div>
      ) : filteredDates.length === 0 ? (
        <Card>
          <CardContent className="text-center py-12">
            <Calendar className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
            <p className="text-lg font-medium text-muted-foreground mb-2">
              {dateFilter ? "No reports found for this search" : "No daily care reports found"}
            </p>
            <p className="text-sm text-muted-foreground">
              {dateFilter ? "Try a different search term" : "Reports will appear here as daily care activities are logged"}
            </p>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-6">
          {filteredDates.map((date) => (
            <div key={date} className="space-y-3">
              <h2 className="text-lg font-semibold text-gray-800 flex items-center space-x-2">
                <Calendar className="w-5 h-5" />
                <span>
                  {new Date(date).toLocaleDateString("en-US", {
                    weekday: "long",
                    year: "numeric",
                    month: "long",
                    day: "numeric"
                  })}
                </span>
              </h2>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Day Report Card */}
                <Card className="cursor-pointer shadow-none">
                  <CardContent className="p-2">
                    <div className="flex items-center justify-between p-3">
                      <div className="flex flex-col items-start justify-start gap-2">
                        <div className="p-2 bg-amber-50 rounded-lg">
                          <Sun className="w-6 h-6 text-amber-600" />
                        </div>
                        <div>
                          <h3 className="font-semibold">Day Report</h3>
                          <p className="text-sm text-muted-foreground">
                            8:00 AM - 8:00 PM
                          </p>
                          <p className="text-xs mt-1 text-green-600">
                            ✓ Archived report
                          </p>
                        </div>
                      </div>
                      <div className="flex flex-col gap-2">
                        <Dialog>
                          <DialogTrigger asChild>
                            <Button 
                              variant="ghost" 
                              size="sm"
                              onClick={() => handleViewReport(date, 'day')}
                            >
                              <Eye className="w-4 h-4 mr-1" />
                              View
                            </Button>
                          </DialogTrigger>
                          <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
                            <DialogHeader>
                              <DialogTitle className="flex items-center space-x-2">
                                <Sun className="w-5 h-5 text-amber-600" />
                                <span>Day Report - {new Date(date).toLocaleDateString()}</span>
                              </DialogTitle>
                              <DialogDescription>
                                All activities logged from 8:00 AM to 8:00 PM
                              </DialogDescription>
                            </DialogHeader>
                            
                            <div className="space-y-4">
                              {selectedReport?.type === 'day' && selectedReport?.date === date && (
                                selectedReportData === undefined ? (
                                  <div className="text-center py-8">
                                    <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto"></div>
                                    <p className="mt-2 text-muted-foreground">Loading report...</p>
                                  </div>
                                ) : (
                                  <div className="space-y-3">
                                    <div className="grid grid-cols-3 gap-4 p-4 bg-amber-50 border border-amber-200 rounded-lg">
                                      <div>
                                        <h4 className="font-medium text-amber-800">Shift Period</h4>
                                        <p className="text-sm text-amber-700">8:00 AM - 8:00 PM</p>
                                      </div>
                                      <div>
                                        <h4 className="font-medium text-amber-800">Total Activities</h4>
                                        <p className="text-sm text-amber-700">{selectedReportData?.activities?.length || 0}</p>
                                      </div>
                                      <div>
                                        <h4 className="font-medium text-amber-800">Completion Rate</h4>
                                        <p className="text-sm text-amber-700">
                                          {selectedReportData?.activities?.length > 0 
                                            ? Math.round((selectedReportData.activities.filter((a: any) => a.status === 'completed').length / selectedReportData.activities.length) * 100)
                                            : 0}%
                                        </p>
                                      </div>
                                    </div>

                                    <div className="space-y-2">
                                      <h4 className="font-medium">Activities Log</h4>
                                      {selectedReportData?.activities && selectedReportData.activities.length > 0 ? (
                                        <div className="space-y-2 max-h-60 overflow-y-auto">
                                          {selectedReportData.activities.map((activity: any, index: number) => (
                                            <div key={index} className="p-3 border border-gray-200 rounded-lg">
                                              <div className="flex justify-between items-start">
                                                <div>
                                                  <p className="font-medium">{activity.taskType}</p>
                                                  <p className="text-sm text-muted-foreground">
                                                    {activity.completedAt ? new Date(activity.completedAt).toLocaleTimeString() : 'Pending'}
                                                  </p>
                                                  {activity.notes && (
                                                    <p className="text-sm text-gray-600 mt-1">{activity.notes}</p>
                                                  )}
                                                </div>
                                                <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                                                  activity.status === 'completed' 
                                                    ? 'bg-green-100 text-green-800'
                                                    : 'bg-yellow-100 text-yellow-800'
                                                }`}>
                                                  {activity.status}
                                                </span>
                                              </div>
                                            </div>
                                          ))}
                                        </div>
                                      ) : (
                                        <p className="text-muted-foreground py-8 text-center">No activities logged for day shift</p>
                                      )}
                                    </div>
                                  </div>
                                )
                              )}
                            </div>
                          </DialogContent>
                        </Dialog>
                        
                        <Button 
                          variant="ghost"
                          size="sm"
                          onClick={() => handleDownloadReport(date, 'day')}
                        >
                          <Download className="w-4 h-4 mr-1" />
                          Download
                        </Button>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                {/* Night Report Card */}
                <Card className="cursor-pointer shadow-none">
                  <CardContent className="p-2">
                    <div className="flex items-center justify-between p-3">
                      <div className="flex flex-col items-start justify-start gap-2">
                        <div className="p-2 bg-indigo-50 rounded-lg">
                          <Moon className="w-6 h-6 text-indigo-600" />
                        </div>
                        <div>
                          <h3 className="font-semibold">Night Report</h3>
                          <p className="text-sm text-muted-foreground">
                            8:00 PM - 8:00 AM
                          </p>
                          <p className="text-xs mt-1 text-green-600">
                            ✓ Archived report
                          </p>
                        </div>
                      </div>
                      <div className="flex flex-col gap-2">
                        <Dialog>
                          <DialogTrigger asChild>
                            <Button 
                              variant="ghost" 
                              size="sm"
                              onClick={() => handleViewReport(date, 'night')}
                            >
                              <Eye className="w-4 h-4 mr-1" />
                              View
                            </Button>
                          </DialogTrigger>
                          <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
                            <DialogHeader>
                              <DialogTitle className="flex items-center space-x-2">
                                <Moon className="w-5 h-5 text-indigo-600" />
                                <span>Night Report - {new Date(date).toLocaleDateString()}</span>
                              </DialogTitle>
                              <DialogDescription>
                                All activities logged from 8:00 PM to 8:00 AM
                              </DialogDescription>
                            </DialogHeader>
                            
                            <div className="space-y-4">
                              {selectedReport?.type === 'night' && selectedReport?.date === date && (
                                selectedReportData === undefined ? (
                                  <div className="text-center py-8">
                                    <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto"></div>
                                    <p className="mt-2 text-muted-foreground">Loading report...</p>
                                  </div>
                                ) : (
                                  <div className="space-y-3">
                                    <div className="grid grid-cols-3 gap-4 p-4 bg-indigo-50 border border-indigo-200 rounded-lg">
                                      <div>
                                        <h4 className="font-medium text-indigo-800">Shift Period</h4>
                                        <p className="text-sm text-indigo-700">8:00 PM - 8:00 AM</p>
                                      </div>
                                      <div>
                                        <h4 className="font-medium text-indigo-800">Total Activities</h4>
                                        <p className="text-sm text-indigo-700">{selectedReportData?.activities?.length || 0}</p>
                                      </div>
                                      <div>
                                        <h4 className="font-medium text-indigo-800">Completion Rate</h4>
                                        <p className="text-sm text-indigo-700">
                                          {selectedReportData?.activities?.length > 0 
                                            ? Math.round((selectedReportData.activities.filter((a: any) => a.status === 'completed').length / selectedReportData.activities.length) * 100)
                                            : 0}%
                                        </p>
                                      </div>
                                    </div>

                                    <div className="space-y-2">
                                      <h4 className="font-medium">Activities Log</h4>
                                      {selectedReportData?.activities && selectedReportData.activities.length > 0 ? (
                                        <div className="space-y-2 max-h-60 overflow-y-auto">
                                          {selectedReportData.activities.map((activity: any, index: number) => (
                                            <div key={index} className="p-3 border border-gray-200 rounded-lg">
                                              <div className="flex justify-between items-start">
                                                <div>
                                                  <p className="font-medium">{activity.taskType}</p>
                                                  <p className="text-sm text-muted-foreground">
                                                    {activity.completedAt ? new Date(activity.completedAt).toLocaleTimeString() : 'Pending'}
                                                  </p>
                                                  {activity.notes && (
                                                    <p className="text-sm text-gray-600 mt-1">{activity.notes}</p>
                                                  )}
                                                </div>
                                                <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                                                  activity.status === 'completed' 
                                                    ? 'bg-green-100 text-green-800'
                                                    : 'bg-yellow-100 text-yellow-800'
                                                }`}>
                                                  {activity.status}
                                                </span>
                                              </div>
                                            </div>
                                          ))}
                                        </div>
                                      ) : (
                                        <p className="text-muted-foreground py-8 text-center">No activities logged for night shift</p>
                                      )}
                                    </div>
                                  </div>
                                )
                              )}
                            </div>
                          </DialogContent>
                        </Dialog>
                        
                        <Button 
                          variant="ghost"
                          size="sm"
                          onClick={() => handleDownloadReport(date, 'night')}
                        >
                          <Download className="w-4 h-4 mr-1" />
                          Download
                        </Button>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}